definitions:
  standard__front_page:
    enabled: false
    menu_name: main
    parent: ''
    expanded: false
    weight: -50
  contact__site_page:
    weight: -47
    menu_name: footer
    parent: ''
    expanded: false
    enabled: true
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
