module:
  abjs: 0
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  antibot: 0
  automated_cron: 0
  backup_migrate: 0
  bg_image_formatter: 0
  blazy: 0
  blazy_ui: 0
  block: 0
  block_content: 0
  breakpoint: 0
  checklistapi: 0
  ckeditor: 0
  coffee: 0
  color: 0
  config: 0
  contact: 0
  contact_block: 0
  contextual: 0
  ctools: 0
  daterange_compact: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  disqus: 0
  ds: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  geolocation: 0
  google_analytics: 0
  help: 0
  history: 0
  hreflang: 0
  image: 0
  imce: 0
  layout_discovery: 0
  libraries: 0
  link: 0
  link_attributes: 0
  linkit: 0
  menu_ui: 0
  metatag: 0
  metatag_facebook: 0
  metatag_google_plus: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  metatag_verification: 0
  metatag_views: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  quickedit: 0
  rdf: 0
  redirect: 0
  responsive_bg_image_formatter: 0
  responsive_image: 0
  schema_article: 0
  schema_event: 0
  schema_item_list: 0
  schema_metatag: 0
  schema_organization: 0
  schema_web_page: 0
  schema_web_site: 0
  search: 0
  seckit: 0
  seo_checklist: 0
  serialization: 0
  shortcut: 0
  simple_sitemap: 0
  slick: 0
  slick_extras: 0
  slick_ui: 0
  slick_views: 0
  system: 0
  taxonomy: 0
  taxonomy_menu: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_accordion: 0
  views_ui: 0
  webform: 0
  webform_templates: 0
  webform_ui: 0
  menu_link_content: 1
  pathauto: 1
  ds_extras: 2
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  foundation: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
profile: standard
