definitions:
  entity:
    - save
    - delete
    - label
  node:
    - save
    - delete
  user:
    - delete
  comment:
    - save
    - delete
  taxonomy_term:
    - save
    - delete
_core:
  default_config_hash: vmMVpPwjPrRP6HxHmjkrKs9TfU1xTJgAbQOhE8xOXss
