features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 0
logo:
  use_default: 1
  path: themes/foundation/assets/img/logo.png
favicon:
  use_default: 0
  path: ''
facebook: 'https://facebook.com'
twitter: 'https://twitter.com'
pinterest: 'https://pinterest.com'
social_facebook: 'https://facebook.com/dellahonestly'
social_twitter: 'https://twitter.com/dellahonestly'
social_pinterest: 'https://pinterest.com/dellahonestly'
social_google: 'https://google.com/dellahonestly'
social_youtube: ''
to_top: 1
search_background_path: 'public://hero_2.jpg'
search_background_upload: ''
favicon_upload: ''
aaa: 'public://Screen Shot 2016-09-29 at 10.51.40_14.png'
search_background: ''
google_maps_api_key: AIzaSyCsvf1PCi_cbI1hejDpVIjNlBrIgolKQwM
